name: Dockerhub
on: workflow_dispatch

env:
  NODE_VERSION: 20

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.PACKAGE_VERSION }}

    steps:
      - name: Set Version
        uses: Nyffels-IT/github-actions-calver-version-generator@v1.0.1

      - name: Current version
        run: 'echo Verion: ${{ env.PACKAGE_VERSION }}'

  build-publish:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code initialization
        run: npm install

      - name: Build code
        run: |
          npm run prebuild
          npm run build

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v3          

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}        
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dist
          pull: true
          push: true
          tags: nyffelsit/html-to-pdf:${{ needs.setup.outputs.version }}, nyffelsit/html-to-pdf:latest               
